# sonar.projectKey=products-api
# sonar.organization=Trokeles
# sonar.sources=.
# sonar.exclusions=**/node_modules/**,**/tests/**
# sonar.tests=tests
# sonar.test.inclusions=tests/**/*.test.js
# sonar.javascript.lcov.reportPaths=coverage/lcov.info
# sonar.login=${SONAR_TOKEN}


sonar.projectKey=JonathanAndresM
sonar.organization=Jonathan Muchewicz
sonar.host.url=https://sonarcloud.io
sonar.login=${SONAR_TOKEN}

# Project settings
sonar.projectName=apiProducts
sonar.projectDescription=API RESTful para la gestión de productos
sonar.projectVersion=1.0

# Paths
sonar.sources=src
sonar.tests=tests
sonar.test.inclusions=**/*.test.js
sonar.javascript.lcov.reportPaths=coverage/lcov.info

# Encoding
sonar.sourceEncoding=UTF-8