name: CI

on:
  push:
    branches: [ main ]

jobs:
  build-and-test:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3

    - name: Usar Node.js
      uses: actions/setup-node@v3
      with:
        node-version: '18'

    - name: Instalar dependencias
      run: npm ci

    - name: Ejecutar tests
      run: npm test

    - name: Análisis SonarCloud
      uses: SonarSource/sonarcloud-github-action@v2
      with:
        organizationKey: Trokeles
        project: products-api
        token: ${{ secrets.SONAR_TOKEN }}
